using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Ch06.DataGridDemo
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            DataContext = new List<PersonInfo>
            {
                new PersonInfo { FirstName = "Bart", LastName="Simpson",Email="bart@runaway.com",IsEmployed=false,Gender=Gender.Male, Avatar=new Uri("Images/Icon-user.png",UriKind.Relative)},
                new PersonInfo { FirstName = "Home", LastName="Simpson",Email="homer@spriengfield.com",IsEmployed=true,Gender=Gender.Male, Avatar=new Uri("Images/Icon-user.png",UriKind.Relative)},
                new PersonInfo { FirstName = "Marge", LastName="Simpson",Email="marge@desparatehousewives.com",IsEmployed=false,Gender=Gender.Female, Avatar=new Uri("Images/Icon-user.png",UriKind.Relative)},
                new PersonInfo { FirstName = "Lisa", LastName="Simpson",Email="lisa@musiclovers.com",IsEmployed=false,Gender=Gender.Female, Avatar=new Uri("Images/Icon-user.png",UriKind.Relative)},
                new PersonInfo { FirstName = "Maggie", LastName="Simpson",Email="maggie@runaway.com",IsEmployed=false,Gender=Gender.Female, Avatar=new Uri("Images/Icon-user.png",UriKind.Relative)},
            };
        }

        private void DgPeople_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.PropertyName == "Avatar")
            {
                e.Cancel = true;
            }
        }

        private void DgPeople_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            grid.Columns[0].DisplayIndex = 5;
        }
    }
}
